name: boed-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - contourpy=1.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - glib=2.84.4
  - glib-tools=2.84.4
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipython=8.15.0
  - jedi=0.19.2
  - jpeg=9f
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250814.1
  - libavif=1.3.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libclang=20.1.8
  - libclang13=20.1.8
  - libcups=2.4.15
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm20=20.1.8
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.33.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libtirpc=1.3.7
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=9.3.0
  - mysql-client=9.3.0
  - mysql-common=9.3.0
  - mysql-devel=9.3.0
  - mysql-libs=9.3.0
  - mysql-server=9.3.0
  - ncurses=6.5
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.0.18
  - packaging=25.0
  - pandas=1.3.4
  - parso=0.8.4
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - ply=3.11
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pygments=2.19.1
  - pyparsing=3.0.9
  - pyqt=6.9.1
  - pyqt5-sip=12.13.0
  - pyqt6-sip=13.10.2
  - python=3.9.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qt-main=6.9.1
  - qt5compat=6.9.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtimageformats=6.9.2
  - qtshadertools=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.1
  - qttranslations=6.9.1
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readline=8.3
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - spirv-tools=2025.1
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - joblib==1.1.0
    - scikit-learn==1.0.2
    - threadpoolctl==2.2.0
